VadimDez/ng2-pdf-viewer

src/pdf-viewer/pdf-viewer.component.ts

Hello,
I am suggesting small but valuable change. It fixes a crash of the pdf-viewer when it is evaluated as a component within a template of another component, who has not been yet fully initialized. In such case the "src" value may not be yet defined, but in the current code loadPDF is called and it crashes and never being executed again. This small patch is trying to avoid this and I hope it will be accepted

Fix the case where src is still not having a value

---

src/pdf-viewer/pdf-viewer.component.ts

When text is rendered canvas has a z-index of 1 to be kept under the text.
But because there is no stacking context anywhere inside `<pdf-viewer>` to encapsulate `z-index`, this can provoke unexpected behavior with user designs like in #39 and #43.
This is one possible fix, another one could be to set the text layer as `position: absolute` instead of the canvas and keep the default z-index behavior.
Workaround in the meantime : 
```css
pdf-viewer {
position: relative;
z-index: 0;
}
```

Create stacking context. fix #39 #43

---

package.json
src/app/app.component.html
src/app/app.component.ts
src/pdf-viewer/pdf-viewer.component.ts

This PR creates a breaking change.
Use an `@Output` instead of a callback to handle afterload events.
I didn't changed the name `after-load-complete` but I think `load` should be enough.

Use @Output for after load events

---

src/pdf-viewer/pdf-viewer.component.ts

this pull request will resolve #140 
cause:
the priority from css more than attribute. if we use css like 
```css
* { font-family: Tahoma } 
```
it will replace all svg font-family attribute. and it make font render incorrect.
so i will convert all `font-family` and `font-size` attribute to inline style to make sure it will not to override by css.
i think another solution may be render in ```iframe```

force inline style to prevent css override font-family and font-size

---

src/pdf-viewer/pdf-viewer.component.ts

Hi! Thanks for the ng2-pdf-viewer component.
I've been using your component in my app, and found out that [original-size] attribute doesn't seem to work when you want to show first page only - [show-all]="false".
You can reproduce it on project demo page:
https://vadimdez.github.io/ng2-pdf-viewer/ 
1. Switch on 'Original size' -> PDF is now in original size.
2. Switch off 'Show all pages' -> PDF is now in scaled size (wrong).
The submitted PR should resolve this bug, pls let me know if smth is wrong, or can be improved.
Thx!

Fixed original size for showAll=false

---

src/pdf-viewer/pdf-viewer.component.ts

Hi there,
In my app I need to show the PDF files of different sizes, basically anything that user can upload. Showing the PDF document in original size is very convenient, but currently there is a problem with large documents, which are not fitting into the viewport. This is not very convenient for the user.
This can be avoided by using [original-size]=false, but this means that all smaller documents will be upscaled and look bad.
I thought it would be good to show the document in original size only if it fits into the viewport, otherwise it should be scaled to max-width to fit.
If you have other ideas on approaching this issue, pls let me know.
p.s. Please find attached example of large PDF - [document.pdf](https://github.com/VadimDez/ng2-pdf-viewer/files/1438108/document.pdf)
Thanks!

Fit original document into the viewport.

---

src/pdf-viewer/pdf-viewer.component.ts

If `PDFJS.workerSrc` isn't overwritten when it's set already, then client code is able to set it to the preferred URL.
Related to issue #162 
For instance, my client code can overwrite `PDFJS.workerSrc` as following:
```ts
export class MyComponent implements OnInit {
ngOnInit() {
window.PDFJS.workerSrc = '/pdf.worker.min.js';
}
}
```

Don't overwrite PDFJS.workerSrc if already set

---

src/app/pdf-viewer/pdf-viewer.component.ts

If browser is resized during the loading of the pdf, an error occurs when trying to access this._pdf before it has been specified.
`ERROR TypeError: Cannot read property 'getPage' of undefined
at e.updateSize (https://vadimdez.github.io/ng2-pdf-viewer/main.ceb4e328854fe17b171f.bundle.js:1:729905)
at https://vadimdez.github.io/ng2-pdf-viewer/main.ceb4e328854fe17b171f.bundle.js:1:727735
at e.invokeTask (https://vadimdez.github.io/ng2-pdf-viewer/polyfills.7bd652c3475ff750ac21.bundle.js:1:22959)
at Object.onInvokeTask (https://vadimdez.github.io/ng2-pdf-viewer/main.ceb4e328854fe17b171f.bundle.js:1:396262)
at e.invokeTask (https://vadimdez.github.io/ng2-pdf-viewer/polyfills.7bd652c3475ff750ac21.bundle.js:1:22880)
at t.runTask (https://vadimdez.github.io/ng2-pdf-viewer/polyfills.7bd652c3475ff750 …

Fix error on resize during loading of pdf

---

src/app/pdf-viewer/pdf-viewer.component.ts

For every new pdf rendered the old worker is not destroyed.
This PR fixes that

fix: Cleanup unused pdf document proxies

---

README.md
src/app/pdf-viewer/pdf-viewer.component.ts

There is a problem with selecting text in browsers other that Firefox, selection jump to the top/bottom of
the page when cursor moves over white space ( space, paragraph, new line etc. ). I am pretty sure the
problem is with additional div.endOfPage element, only Firefox disables user-select on it.
When you set textLayerMode to 'ENHANCED' then it works as expected.

enable setting render text mode to enchanced

---

package-lock.json
package.json
src/app/pdf-viewer/pdf-viewer.component.ts

This should fix [issue-#322](https://github.com/VadimDez/ng2-pdf-viewer/issues/322) (I accidentally named the branch incorrectly) and suppress the z-lib warning according to [mozilla/pdf.js#9924](https://github.com/mozilla/pdf.js/pull/9924) by updating to `pdfjs-dist@2.0.943`.
`pdfjs-dist@2.0.943` adds `browser: { 'zlib': false }` to the npmManifest.

suppress z-lib warning in angular6+

---

src/app/pdf-viewer/pdf-viewer.component.ts
src/app/utils/event-bus-utils.ts

After clicking an internal navigation link the current page number will now be correct for single page view mode. 
Issue #474

update page number upon page changing event

---

src/app/pdf-viewer/pdf-viewer.component.ts

This change mirrors the change done for SInglePageViewer
Verified works locally on scrolling, find, zoom and other functionality.
Fixes
Issue #223

Emit pageChange on MultiPageViewer

---

src/app/pdf-viewer/pdf-viewer.component.ts

Bugfix #539
Stop multiple emits of pageChange, which was causing a multi-page view problem when the user switched pages rapidly and repeatedly.

Bugfix #539 Only emit pageChage on actual change

---

README.md
src/app/app.component.html
src/app/app.component.ts
src/app/material.module.ts
src/app/pdf-viewer/pdf-viewer.component.ts

give the possibility to choose between page-fit, page-width and page-height when original-size is false, and setting zoom
Note:Not sure how versioning is controlled in PR

feat(zoom): configurability of scale (page-width/page-height/page-fit)

---

src/app/pdf-viewer/pdf-viewer.component.scss

If we do not do that it would be overwritten by eg Ionic and the border does not look like as expected.

fix: explicitly set box-sizing of a page to initial

---

browserslist
src/app/pdf-viewer/pdf-viewer.component.ts
src/index.html
tsconfig.json

Current [demo](https://vadimdez.github.io/ng2-pdf-viewer/) crashes on IE.

Issue #478 IE

---

README.md

I see two possibilities in the usage:
1. `[zoom-scale]="'page-width'"`
2. `zoom-scale="page-width"`

Fix in docs

---

src/app/pdf-viewer/pdf-viewer.component.ts

Currently, there are a lot of leaks:
Most leaks are coming from the `pdfjs-dist` package, it adds a lot of event listeners and never removes them:
By unreferencing `loadingTask` I was able to unreference some `pdfjs-dist` resources that were created by `loadingTask` internally.

fix: release some memory leaks

---

src/app/pdf-viewer/pdf-viewer.component.scss

Giving the host `display: block` makes him immediately visible. `position: relative` is there to prevent https://github.com/VadimDez/ng2-pdf-viewer/issues/811.

Give sane default to host

---

src/app/pdf-viewer/pdf-viewer.component.scss

latest changes reintroduced a variant of https://github.com/VadimDez/ng2-pdf-viewer/issues/505
for more info see: https://developer.mozilla.org/de/docs/Web/CSS/::selection.

fix css selector for text selection in chrome

---

src/app/pdf-viewer/pdf-viewer.component.ts

Resets the lastLoaded value when loading a document fails

fix can't load document after error

---

src/app/app.component.ts

As PDFJS refactored the PDFLinkService to use goToDestination, reflect this in example app.

fix: correct broken outline navigation

---

src/app/pdf-viewer/pdf-viewer.component.ts

Solution explained on the issue :
Add this._latestScrolledPage = 0; on clear method to reset this value on pdfLoad and correct the current bug.

fix #947 : reset this._latestScrolledPage on clear method

---

README.md
package.json
src/app/pdf-viewer/pdf-viewer.component.spec.ts
src/app/pdf-viewer/pdf-viewer.component.ts

some environments can have multiple versions of the pdf viewer in the same browser instance, so url overrides need to have the ability to be specific to a version

feat: Support version specific pdf.worker.js url

---

README.md

Library is not using cloudflare from what I can see in the code.

Update documentation pdfWorkerSrc jsdelivr

---

package-lock.json
package.json
src/app/pdf-viewer/pdf-viewer.component.ts
src/app/pdf-viewer/typings.ts
src/app/utils/event-bus-utils.ts
tsconfig.json

Newer versions of pdf.js > 3.x seem to have a lot of bug fixes so I took a crack at this but I'll be honest Im not sure of all the exact issues with supporting older versions of things. 
This seemed straightforward for the most part, a couple build issues (linked thread in code comment) two parts of the API changed, viewer `textLayerMode` & `_setScale`. Tough to find good docs so did what I could here. 
Tests pass locally.
Thanks again for the great project & maintaining it

Chore: Update pdfjs-dist to 3.10.111

---

README.md

Changed README.md anchors to link to the current file, instead of opening up the code viewer tree if not in it already.

fix(docs): README anchors navigating to file tree

---

package-lock.json
package.json
src/app/pdf-viewer/pdf-viewer.component.spec.ts
src/app/pdf-viewer/pdf-viewer.component.ts

Hey glad to see the project is still going! Thanks for merging my other update PR 🙏
Not to be annoying but I figured we might as well go to the latest 3.x, I also included a change to disable JS execution which is an acceptable solution to https://www.cve.org/CVERecord?id=CVE-2024-4367 AFAIK
Closes #1088
Supersedes #1089

Chore: update pdfjs to 3.11.174, resolve CVE

---

src/app/pdf-viewer/pdf-viewer.component.ts

avoid errors that prevents switching pdf documents, as the  AnnotationEditorUIManager.destroy errors about uninitialized properties.

Explicitely switch AnnotationEditor off

---

src/app/pdf-viewer/pdf-viewer.component.scss
src/app/pdf-viewer/pdf-viewer.component.ts

- Fix for #999 
- Also fixes that rotated documents where overflowing and thus showing an unnecessary scrollbar. Taken from https://github.com/mozilla/pdf.js/blob/master/web/text_layer_builder.css#L25

Fix #999: Ensure that the rotation in the viewer is not set too early

---

README.md

In v4.x of PDF.js the build files have changed from .js to .mjs
This commit updates the example usage in the README from .js to .mjs to closer align to the most common use case for this section

fix: Update documentation to reference 4.x pdf.js worker extension

---

package-lock.json
package.json

Fix: lock pdfjs version

---

src/app/pdf-viewer/pdf-viewer.component.ts

Caused by https://github.com/VadimDez/ng2-pdf-viewer/pull/1098
Closes #1145
Let me know if I've missed anything here, of course.
Seems to fix the flash-of-unzoomed-pdf (FOUP):
https://github.com/user-attachments/assets/259b4343-23ce-480d-95f9-799c1431d739

Fix: use page init for first updateSize
